apiVersion: v1
kind: Service
metadata:
  name: "poc-pipeline-service"
spec:
  selector: 
    app: "poc-pipeline"
  type: ClusterIP
  ports:
    - name: "poc-pipeline-service"
      port: 9000
      targetPort: 8080
      protocol: TCP
    