apiVersion: apps/v1
kind: Deployment
metadata:
  name: "poc-pipeline"
  labels:
    app: "poc-pipeline"
spec:
  selector:
    matchLabels:
      app: "poc-pipeline"
  replicas: 3
  template:
    metadata:
      name: "poc-pipeline"
      labels:
        app: "poc-pipeline"
    spec:
      containers:
        - name : "poc-pipeline"
          image: "tbaragao/poc-pipeline:v3"
          env:
            - name: "MyObject__Name" # Para Dotnet precisa ser __ no lugar do . 
              value: "Bazinga"
            - name: "MyObject__Age"
              value: "49"
