apiVersion: v1
kind: Service
metadata:
  name: mysql-h # Nome que será utilizado na config do StatefulSet do ServiceName
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
  clusterIP: None # Define o serviço como Headless

